laetificat_admin:
    resource: "@LaetificatAdminBundle/Controller/"
    type:     annotation
    prefix:   /

laetificat_frontend:
    resource: "@LaetificatFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

laetificat_common:
    resource: "@LaetificatCommonBundle/Controller/"
    type:     annotation
    prefix:   /
