security:
    encoders:
        Laetificat\CommonBundle\Entity\User:
            algorithm: bcrypt

    providers:
        laetificat_database:
            entity:
                class: LaetificatCommonBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern: ^/admin
            http_basic: ~
            provider: laetificat_database
